[package]
name = "graphene-rs"
license = "MIT"
homepage = "https://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
keywords = ["graphene", "graphene-rs", "gtk", "gtk-rs", "gnome", "GUI"]
readme = "README.md"
documentation = "https://gtk-rs.org/docs/graphene/"
version = "0.1.0"
description = "Rust bindings for the Graphene library"
repository = "https://github.com/gtk-rs/graphene"
build = "build.rs"
exclude = [
    "gir-files/*",
]

[lib]
name = "graphene"

[features]
default = ["v1_10"]
v1_10 = ["graphene-sys/v1_10"]
dox = ["graphene-sys/dox", "glib/dox"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs"]

[package.metadata.docs.rs]
features = ["dox", "embed-lgpl-docs"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.3"
optional = true
git = "https://github.com/gtk-rs/lgpl-docs"

[dependencies]
libc = "0.2"
glib-sys = { git = "https://github.com/gtk-rs/sys" }
gobject-sys = { git = "https://github.com/gtk-rs/sys" }
glib = { git = "https://github.com/gtk-rs/glib" }

[dependencies.graphene-sys]
path = "graphene-sys"

[dev-dependencies]
gir-format-check = "^0.1"
